:docinfo:
include::./common_docinfo_vars.adoc[]
include::./suse-trd_contrib-guide-vars.adoc[]
[#art-{article-id}]

// = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =
// SUSE Technical Reference Documentation: Contributor's Guide
// 
// = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =


// - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
// organization - do NOT modify
// -
:trd: Technical Reference Documentation
:type: Getting Started
// - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -


= {doctitle}: {docsubtitle}



== Introduction

=== Motivation

// = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =
// Provide a motivation for the document in 2-4 sentences to identify:
//   - what the document is about
//   - why it may be of interest to the reader (e.g., a use case)
//   - what products are being highlighted
// Include an approved SUSE | Partner logo lock-up if possible
// Include any additional, relevant details
// = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =

{trd-portal}[{trd-brand}] ({trd}) is the open collection of contributed, high quality, technical guidance for solutions that address real-world use cases with SUSE, partner, and community components.
The {trd} collection is implemented as code, with source files managed and maintained in the {trd-repo}[{trd} GitHub repository].
Both rendered documentation and source code are open source licensed and freely available.

[NOTE]
====
Contributions to {trd-long} are expected to meet SUSE's high standards for quality.
However, as voluntary contributions, SUSE makes no guarantee for their accuracy, completeness, or appropriateness for specific situations or environments.
====

Contributions to {trd} come from SUSE, partners, and the wider community.
These are welcome and encouraged.
Minor fixes for existing documentation can be submitted easily through the _Report an issue_ links in the HTML version of any document.
For a new document, a successful contributor will require deeper familiarity with the {trd-long} style, structure, tools, and workflows.


=== Audience

This guide is intended for those interesting in contributing high-quality, technical documentation to {trd-long}.



=== Scope

This guide aims to provide contributors with a basic introduction and reference resource for developing and submitting {trd-alt} to the collection.


In this document, you learn about:

* <<Prerequisites>>
* <<Documentation types>>
* <<Workflows>>
* <<Repository structure>>
* <<Workspace setup>>
* <<Document templates>>
* <<Writing style>>
* <<AsciiDoc coding>>



== Prerequisites

{trd-alt} are documentation-as-code.
They are built from a collection of {asciidoc-url}[AsciiDoc] and {docbook-url}[DocBook] source files that are rendered into published formats, such as HTML and PDF.
Development often begins in a favorite word processor or shared document editing environment, making it easier to contribute content without learning to code.
But, ultimately, these documents must be implemented in code.

Those who only intend to contribute content outside the documentation-as-code environment are still encouraged to become familiar with documentation types and SUSE Documentation Style.


Those who will be working in the documentation-as-code environment will need the following:

* A plain text editor
+
[NOTE]
====
Your editor should save files encoded to https://en.wikipedia.org/wiki/UTF-8[UTF-8] and only end lines with the linefeed (LF) character.

See also {git-line-endings-url}[Configuring Git to handle line endings].
====

* {github-url}[GitHub] account and basic Git skills

* Basic understanding of the {asciidoc-url}[AsciiDoc] markup language
//
+
See AsciiDoc introduction for a brief overview of the markup language used to create {trd-alt} with some examples.

* DAPS toolchain (for rendering documents)
+
--
You have two options for DAPS:

* {daps-install-url}[Install DAPS] and its dependencies directly, including the latest {suse-xsl-url}[SUSE XSL Stylesheets].

* Use the {daps2docker-url}[DAPS2Docker] container implementation.
--
+
[TIP]
====
For those using {vscode-url}[Visual Studio Code (VS Code)] as their preferred integrated development editor (IDE), the {daps-vscode-url}[vscode-daps plugin] can make it easier to run selected DAPS commands from within the VSCode editor.
====

* PDF viewer and Web browser (for reviewing rendered documents).



== Documentation types

{trd-alt} can be divided into three types:

* *Getting Started Guide*
//
+
A solution introduction with step-by-step guidance for installation and configuration for a use case.

* *Reference Implementation*
//
+
An architectural reference with deployment guidance for a solution involving elements of the SUSE portfolio.

* *Reference Configuration*
//
+
An architectural reference with deployment guidance for a solution featuring SUSE and partner components.




== Workflows

//include::suse-trd_contrib-workflow.adoc[]





== Repository structure

// = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =
// Section: Source repository structure
// = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =

The {trd-repo}[{trd-long} source Git repository] is hosted on GitHub to facilitate management and collaboration.
A Git repository is a directory or folder in a file system along with metadata and tooling for tracking and managing file revisions.
One of your first steps as a contributor is to clone the repository to your local system, where you will edit the source files for your document.
Thus, it is helpful to have a general understanding of the repository's structure and contents.

The top-level directory structure of the {trd} source repository is illustrated in the listing below.

[listing]
----
.
├── common <1>
├── contributors <2>
├── kubernetes <3>
├── linux
└── references <4>
----
<1> `common` contains shared content, scripts, and templates.
<2> `contributors` contains source files for this contributors' guide.
<3> `kubernetes` and `linux` contain archived reference sources.
<4> `references` contains *source files for current references*.


As a contributor, your efforts will be focused inside the `references` directory.

[listing]
----
references
├── bin -> ../common/bin
...
├── everpure
...
├── jupyter
...
├── hitachi
...
├── kubeflow
...
├── supermicro
...
├── suse
...
├── veeam
...
----

Here, you find subdirectories that identify the featured technology partner or community project.
For example, the source files for a reference featuring JupyterHub, which is part of Project Jupyter, would be found in the `jupyter` directory.
If an appropriate directory for your technical references does not already exist, you can create one during the workspace setup process.
There is also a `suse` directory (containing document sources that feature only SUSE components) and a symbolic link to a `bin` directory (containing helpful scripts for contributors).


[TIP]
====
For a technical reference featuring more than one component provider, select only one for the directory name.
As a general rule, the selected partner provides the component at the top of the software stack that delivers a unique, highlighted capability.
If important, additional component providers can be noted in the names of your source files.
====


Your work as a contributor is inside a provider directory.
The structure and contents of an example provider directory are illustrated below.

[listing]
----
provider
├── DC-gs_suse-prod_partner-product <1>
├── adoc <2>
│   ├── common_docinfo_vars.adoc -> ../../../common/adoc/common_docinfo_vars.adoc <3>
│   ├── common_gfdl1.2_i.adoc -> ../../../common/adoc/common_gfdl1.2_i.adoc
│   ├── common_sbp_legal_notice.adoc -> ../../../common/adoc/common_sbp_legal_notice.adoc
│   ├── common_trd_legal_notice.adoc -> ../../../common/adoc/common_trd_legal_notice.adoc
│   ├── gs_suse-prod_partner-product.adoc <4>
│   ├── gs_suse-prod_partner-product-docinfo.xml <5>
│   └── gs_suse-prod_partner-product-vars.adoc <6>
├── images -> media
└── media <7>
    └── src
        ├── png
        │   └──  get-vol-snapshots.png
        └── svg
            └── suse.svg -> ../../../../../common/images/src/svg/suse.svg
----
<1> Doc Config (DC) file
//
+
There is only one DC file per technical reference.
It specifies the location of the main content, the stylesheet to use for formatting, the draft state, and more.
You typically only need to edit this file once, when you are ready to publish and you turn off draft mode.

<2> `adoc` directory
//
+
The `adoc` directory contains content and metadata files, as described below.

<3> Common files
//
+
Your published document automatically includes standard content contained in these symbolically linked files.

<4> Main content file
//
+
Your main content file, in AsciiDoc markup language, is where you add the content you wish to see in the published document.

<5> DocBook metadata (docinfo.xml) file
//
+
The DocBook metadata file, in XML format, provides information about your document.
You typically only need to make minor edits to the provided templates.

<6> Vars file
//
+
The vars file contains variable (or document attribute) definitions.
These include the product names and versions, website and documentation URLs, document title, author names, and more.
These variables are then substituted for text in the main content file and DocBook metadata file to ensure consistency throughout your document.
Additionally, using variables makes it easier to make future updates, such as if a product name or website URL change.

<7> `media` directory
//
+
The `media` directory contains all media files, such as diagrams and screenshots, you wish to appear in your published document.
Media files must be organized by file type under `media/src`.
//
+
Many image file types are supported, but preference is given to:
+
--
* https://www.w3.org/Graphics/SVG/[Scaled Vector Graphics] or 'SVG' is a widely-deployed, royalty-free, vector graphics format developed and maintained by the W3C.
A vector graphics image is rendered from a set of instructions that defines the image from basic, geometric shapes.
This allows SVGs to be resized without loss of clarity.
SVGs are typically used for logos and architectural diagrams.
* https://en.wikipedia.org/wiki/PNG[Portable Network Graphics] or 'PNG' is a raster graphics format.
A raster image encodes information (like position, color, or brightness)  for each pixel (picture element) that makes up the image.
PNG uses lossless compression, allowing PNGs to be edited and resaved without loss of clarity (unlike Joint Photographic Experts Group or 'JPEG' images).
Scaling raster images can introduce artifacts.
This is particularly apparent when images are enlarged.
Choose image resolutions to minimize these artifacts.
--
+
[NOTE]
====
Legacy processes referenced an `images` directory.
Today, `images` is simply a symbolic link to the `media` directory and is maintained for compatibility.
====



== Document templates

// = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =
// Outline use of setup scripts and templates
// = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =

Your {trd} documentation project relies on different types of source files, placed in specific locations within the repository's directory structure.
The files and structures can be created from scratch.
But you can use the provided automation tools to generate a framework for you, including templates for your source files.




== Workspace setup

// Integrate GS content here around refsetup.sh




== Writing style

//include::suse-trd_contrib-style.adoc[]


== AsciiDoc coding

//include::suse-trd_contrib-asciidoc.adoc[]




== Summary

// = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =
// Summarize:
// - Motivation (1 sentence)
// - What was covered (1-2 sentences)
// - Next steps (unordered list of 2-4 further learning resources)
// = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =

{trd-long} is a repository of high quality documentation for solutions that address real-world use cases with featured SUSE, partner, and community components.

This document provides an overview of the tools, techniques, workflows, and styles that you will use to make successful contributions to {trd}.


== Terminology

//include::suse-trd_contrib-terminology.adoc[]





// = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =
// Do not modify below this break.
// = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =

++++
<?pdfpagebreak?>
++++


:leveloffset: 0

== Legal notice
include::common_trd_legal_notice.adoc[]

++++
<?pdfpagebreak?>
++++


:leveloffset: 0
include::common_gfdl1.2_i.adoc[]

//end
