// = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =
// Section: Source repository structure
// = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =

The {trd-repo}[{trd-long} source repository] is a Git repository, hosted on GitHub to facilitate management and collaboration.
A Git repository is a directory or folder in a file system along with metadata and tooling for tracking and managing file revisions.
One of your first steps as a contributor is to clone the repository to your local system, where you will edit the source files for your document.
Thus, it is helpful to have a general understanding of the repository's structure and contents.

The top-level of the {trd} repository contains the following directories:

[listing]
----
.
├── common <1>
├── contributors <2>
├── kubernetes <3>
├── linux <4>
└── references <5>
----
<1> `common` contains shared content, scripts, and templates.
<2> `contributors` contains source files for this contributors' guide.
<3> `kubernetes` contains archived, Kubernetes-focused references.
<4> `linux` contains archived, Linux-focused references.
<5> `references` contains *source files for current references*.


As a contributor, your work will focus inside the `references` directory.
It is subdivided into directories (or subdirectories) that are named for a featured partner or project.
For example, a technical reference focused on Project Jupyter, might be named, `jupyter`.
In these directories, the source files for all technical references (and their revisions) featuring the named partner or project are maintained.

[NOTE]
====
If a technical reference features more than one partner or project, one is selected for the directory name.
Additional partners or projects can be highlighted in the names of your source files.
====

Two other items appear in the `references` directory.
They are a `suse` directory, for those technical references that only feature SUSE components, and a symbolic link, `bin`, to a directory containing helpful programs.


Take a look next inside a partner or project directory.
Here, you find a collection similar to the listing below.

[listing]
----
partner
├── adoc
│   ├── common_docinfo_vars.adoc -> ../../../common/adoc/common_docinfo_vars.adoc
│   ├── common_gfdl1.2_i.adoc -> ../../../common/adoc/common_gfdl1.2_i.adoc
│   ├── common_sbp_legal_notice.adoc -> ../../../common/adoc/common_sbp_legal_notice.adoc
│   ├── common_trd_legal_notice.adoc -> ../../../common/adoc/common_trd_legal_notice.adoc
│   ├── gs_virtualization_partner-product.adoc
│   ├── gs_virtualization_partner-product-docinfo.xml
│   └── gs_virtualization_partner-product-vars.adoc
├── DC-gs_virtualization_partner-product
├── images -> media
└── media <7>
    └── src
        ├── png
        ├── get-vol-snapshots.png
        └── svg
            └── suse.svg -> ../../../../../common/images/src/svg/suse.svg
----
<1> *Doc Config (DC) file*: There is one DC file for each documentation deliverable in which you specify parameters that define the name of the main content file, the rendering stylesheet, the revision date, and so on.
<2> *_adoc_ directory*: Contains your AsciiDoc content files and your DocBook metadata file.
<3> *Main content file*: This plain text file, formatted with the https://asciidoc.org/[AsciiDoc] markup language, is where you write most of the text of your document.
You can use the `include` directive to merge content from other AsciiDoc files during the rendering process.
<4> *DocBook metadata (docinfo.xml) file*: This file specifies metadata about your document, including title, author information, cover logo file, and executive summary.
Much of this information is actually defined as document attributes (variables) in your main content file and referenced here to save you from having to type the same information twice.
<5> *_media_ directory*: You can include logos, diagrams, screenshots, and other images in your guides.
These media files are stored in subdirectories by file type under _media/src_.
Many image file types are supported, but preference is given to:
+
--
* https://www.w3.org/Graphics/SVG/[Scaled Vector Graphics] or 'SVG' is a widely-deployed, royalty-free, vector graphics format developed and maintained by the W3C.
A vector graphics image is rendered from a set of instructions that defines the image from basic, geometric shapes.
This allows SVGs to be resized without loss of clarity.
SVGs are typically used for logos and architectural diagrams.
* https://en.wikipedia.org/wiki/PNG[Portable Network Graphics] or 'PNG' is a raster graphics format.
A raster image encodes information (like position, color, or brightness)  for each pixel (picture element) that makes up the image.
PNG uses lossless compression, allowing PNGs to be edited and resaved without loss of clarity (unlike Joint Photographic Experts Group or 'JPEG' images).
Scaling raster images can introduce artifacts.
This is particularly apparent when images are enlarged.
Choose image resolutions to minimize these artifacts.
--
+
[NOTE]
====
In the "entity" directory, _images_ is a symbolic link to the _media_ directory, and is used to maintain compatibility with existing processes and tooling.
====




