:docinfo:
include::./common_docinfo_vars.adoc[]
include::./suse-trd_contrib-guide_vars.adoc[]
[#art-{article-id}]

// = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =
// SUSE Technical Reference Documentation: Contributor's Guide
// 
// = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =


// - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
// organization - do NOT modify
// -
:trd: Technical Reference Documentation
:type: Getting Started
// - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -


= {title}: {subtitle}



== Introduction

=== Motivation

// = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =
// Provide a motivation for the document in 2-4 sentences to identify:
//   - what the document is about
//   - why it may be of interest to the reader (e.g., a use case)
//   - what products are being highlighted
// Include an approved SUSE | Partner logo lock-up if possible
// Include any additional, relevant details
// = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =

{trd-portal}[{trd-long}] ({trd})is an open collection of high quality guidance for solutions that address real-world use cases with featured SUSE, partner, and community components.
Documents are modular and rendered from multiple source files.
These source files are freely available and open source licensed in the {trd-repo}[GitHub repository].


{trd} can be generally divided into four types:

* *Getting Started Guide*
//
+
Solution introduction with step-by-step guidance for installation and configuration for a use case.

* *Reference Implementation*
//
+
Introductory architectural approach and basis for deployment of solution with the SUSE portfolio.

* *Reference Configuration*
//
+
Reference Implementation with specified partner hardware and software components.

* *Enterprise Architecture*
//
+
Architectural overview of solution from an enterprise landscape perspective.


Community engagement with {trd} is encouraged.
In addition to accessing
You can easily submit quick fixes and even section updates through _Report an issue_ links in the HTML version of any document.

If you have an interest in contributing a new document, you first should become familiar with the style, tools, and workflows of a successful contributor.



=== Scope

// = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =
// Specify what this guide covers in no more than 2 sentences.
// = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =

This guide outlines style, tools, and workflows for successful contributions to {trd}.


=== Audience

// = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =
// Identify for whom this document is intended, perhaps with:
//   - topics of interests (e.g., machine learning, security, etc.)
//   - job roles (e.g., developer, administrator, platform architect, etc.)
//   - required skills
// = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =

This document is intended for architects, engineers, and technical writers who would like to contribute to {trd}.



== Prerequisites

// = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =
// Identify any prerequisites the reader would need
// in order to follow the steps of this guide.
// - Link to existing resources whenever possible.
// - Keep this section brief but elaborate as needed.
// = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =


Contributors to {trd-alt} need the following:

* A plain text editor
+
[NOTE]
====
Your editor should save files encoded to https://en.wikipedia.org/wiki/UTF-8[UTF-8] and only end lines with the linefeed (LF) character.

See also {git-line-endings-url}[Configuring Git to handle line endings].
====

* {github-url}[GitHub] account and basic Git skills

* Basic understanding of the {asciidoc-url}[AsciiDoc] markup language
//
+
See <<AsciiDoc>>.

* DAPS toolchain (for rendering documents)
//
+
--
You have two options for DAPS:

* {daps-install-url}[Install DAPS] and its dependencies directly, including the latest {suse-xsl-url}[SUSE XSL Stylesheets].

* Use the {daps2docker-url}[DAPS2Docker] container implementation.
--
+
See <<DAPS>> for more information.

* PDF viewer and Web browser (for reviewing rendered documents)


== Terminology

include::suse-trd_contrib-terminology.adoc[]



== Workflow

include::suse-trd_contrib-workflow.adoc[]



== Repository structure

// = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =
// Describe the general file and directory structure
// = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =

{trd} is both a {trd-portal}[website] with links to published documents and a {trd-repo}[GitHub repository] of their source files.
As a contributor, you need a general understanding of the structure of the source repository.


The repository's top-level directory structure is:

[listing]
----
.
├── common                     # common content files, templates, and scripts
├── contributors               # {title} source files
├── kubernetes                 # older source collection of Kubernetes-focused solution documentation
├── linux                      # older source collection of Linux-focused solution documentation
└── references                 # current source collection of solution documentation
----

Contributors work exclusively inside the `references` directory.

[listing]
----
references/
├── bin -> ../common/bin
├── portworx
└── suse
----


=== Getting started guide structure

// subsection: repository and document structure for GSGs
include::suse-trd_contrib-gs-structure.adoc[]


=== Reference Implementation and Reference Configuration structure

Coming soon.
// subsection: repository and document structure for RIs and RCs
// include::suse-trd_contrib-rirc-structure.adoc[] - from Bryan



== Templates and framework

// = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =
// Outline use of setup scripts and templates
// = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =

Your {trd} documentation project relies on different types of source files, placed in specific locations within the repository's directory structure.
The files and structures can be created from scratch.
But you can use the provided automation tools to generate a framework for you, including templates for your source files.



=== Getting started guides

include::suse-trd_contrib-gs-templates.adoc[]


=== Reference implementations and reference configurations

Coming soon.
// include::suse-trd_contrib-rirc-templates.adoc[]



== Style

include::suse-trd_contrib-style.adoc[]


== AsciiDoc

include::suse-trd_contrib-asciidoc.adoc[]


== DAPS

include::suse-trd_contrib-daps.adoc[]


== Summary

// = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =
// Summarize:
// - Motivation (1 sentence)
// - What was covered (1-2 sentences)
// - Next steps (unordered list of 2-4 further learning resources)
// = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =

{trd-long} is a repository of high quality documentation for solutions that address real-world use cases with featured SUSE, partner, and community components.

This document provides an overview of the tools, techniques, workflows, and styles that you will use to make successful contributions to {trd}.





// = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =
// Do not modify below this break.
// = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =

++++
<?pdfpagebreak?>
++++


:leveloffset: 0

== Legal notice
include::common_trd_legal_notice.adoc[]

++++
<?pdfpagebreak?>
++++


:leveloffset: 0
include::common_gfdl1.2_i.adoc[]

//end
