:docinfo:
include::./common_docinfo_vars.adoc[]
include::./suse-trd_contrib-guide-vars.adoc[]
[#art-{article-id}]

// = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =
// SUSE Technical Reference Documentation: Contributor's Guide
// 
// = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =


// - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
// organization - do NOT modify
// -
:trd: Technical Reference Documentation
:type: Getting Started
// - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -


= {doctitle}: {docsubtitle}



== Introduction

=== Motivation

// = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =
// Provide a motivation for the document in 2-4 sentences to identify:
//   - what the document is about
//   - why it may be of interest to the reader (e.g., a use case)
//   - what products are being highlighted
// Include an approved SUSE | Partner logo lock-up if possible
// Include any additional, relevant details
// = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =

{trd-portal}[{trd-brand}] ({trd}) is the open collection of contributed, high quality, technical guidance for solutions that address real-world use cases with SUSE, partner, and community components.
The {trd} collection is implemented as code, with source files managed and maintained in the {trd-repo}[{trd} GitHub repository].
Both rendered documentation and source code are open source licensed and freely available.

[NOTE]
====
Contributions to {trd-long} are expected to meet SUSE's high standards for quality.
However, as voluntary contributions, SUSE makes no guarantee for their accuracy, completeness, or appropriateness for specific situations or environments.
====

Contributions to {trd} come from SUSE, partners, and the wider community.
These are welcome and encouraged.
Minor fixes for existing documentation can be submitted easily through the _Report an issue_ links in the HTML version of any document.
For a new document, a successful contributor will require deeper familiarity with the {trd-long} style, structure, tools, and workflows.


=== Audience

This guide is intended for those interesting in contributing high-quality, technical documentation to {trd-long}.



=== Scope

This guide aims to provide contributors with a basic introduction and reference resource for developing and submitting {trd-alt} to the collection.


In this document, you learn about:

* <<Prerequisites>>
* <<Documentation types>>
* <<Workflows>>
* <<Repository structure>>
* <<Workspace setup>>
* <<Document templates>>
* <<Writing style>>
* <<AsciiDoc coding>>



== Prerequisites

{trd-alt} are documentation-as-code.
They are built from a collection of {asciidoc-url}[AsciiDoc] and {docbook-url}[DocBook] source files that are rendered into published formats, such as HTML and PDF.
Development often begins in a favorite word processor or shared document editing environment, making it easier to contribute content without learning to code.
But, ultimately, these documents must be implemented in code.

Those who only intend to contribute content outside the documentation-as-code environment are still encouraged to become familiar with documentation types and SUSE Documentation Style.


Those who will be working in the documentation-as-code environment will need the following:

* A plain text editor
+
[NOTE]
====
Your editor should save files encoded to https://en.wikipedia.org/wiki/UTF-8[UTF-8] and only end lines with the linefeed (LF) character.

See also {git-line-endings-url}[Configuring Git to handle line endings].
====

* {github-url}[GitHub] account and basic Git skills

* Basic understanding of the {asciidoc-url}[AsciiDoc] markup language
//
+
See AsciiDoc introduction for a brief overview of the markup language used to create {trd-alt} with some examples.

* DAPS toolchain (for rendering documents)
+
--
You have two options for DAPS:

* {daps-install-url}[Install DAPS] and its dependencies directly, including the latest {suse-xsl-url}[SUSE XSL Stylesheets].

* Use the {daps2docker-url}[DAPS2Docker] container implementation.
--
+
[TIP]
====
For those using {vscode-url}[Visual Studio Code (VS Code)] as their preferred integrated development editor (IDE), the {daps-vscode-url}[vscode-daps plugin] can make it easier to run selected DAPS commands from within the VSCode editor.
====

* PDF viewer and Web browser (for reviewing rendered documents).



== Documentation types

{trd-alt} can be divided into three types:

* *Getting Started Guide*
//
+
A solution introduction with step-by-step guidance for installation and configuration for a use case.

* *Reference Implementation*
//
+
An architectural reference with deployment guidance for a solution involving elements of the SUSE portfolio.

* *Reference Configuration*
//
+
An architectural reference with deployment guidance for a solution featuring SUSE and partner components.




== Workflows

//include::suse-trd_contrib-workflow.adoc[]





== Repository structure

include::suse-trd_contrib-repo-structure.adoc[]

== Document templates

// = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =
// Outline use of setup scripts and templates
// = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =

Your {trd} documentation project relies on different types of source files, placed in specific locations within the repository's directory structure.
The files and structures can be created from scratch.
But you can use the provided automation tools to generate a framework for you, including templates for your source files.




== Workspace setup

// Integrate GS content here around refsetup.sh




== Writing style

//include::suse-trd_contrib-style.adoc[]


== AsciiDoc coding

//include::suse-trd_contrib-asciidoc.adoc[]




== Summary

// = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =
// Summarize:
// - Motivation (1 sentence)
// - What was covered (1-2 sentences)
// - Next steps (unordered list of 2-4 further learning resources)
// = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =

{trd-long} is a repository of high quality documentation for solutions that address real-world use cases with featured SUSE, partner, and community components.

This document provides an overview of the tools, techniques, workflows, and styles that you will use to make successful contributions to {trd}.


== Terminology

//include::suse-trd_contrib-terminology.adoc[]





// = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =
// Do not modify below this break.
// = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =

++++
<?pdfpagebreak?>
++++


:leveloffset: 0

== Legal notice
include::common_trd_legal_notice.adoc[]

++++
<?pdfpagebreak?>
++++


:leveloffset: 0
include::common_gfdl1.2_i.adoc[]

//end
