// = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =
// Section: Source repository structure
// = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =

{trd-long} is both a {trd-portal}[Web portal] for accessing published documents and a {trd-repo}[source repository] for managing document source files.
As a contributor, you need a general understanding of the structure of the source repository.


A high-level directory view of the repository is illustrated by the listing below.

[listing]
----
.
в”њв”Ђв”Ђ common <1>
в”њв”Ђв”Ђ contributors <2>
в”њв”Ђв”Ђ kubernetes <3>
в”њв”Ђв”Ђ linux <4>
в””в”Ђв”Ђ references <5>
----
<1> shared content, scripts, and templates
<2> source files for this contributors' guide
<3> source files for archived references focused on Kubernetes
<4> source files for archived references focused on Linux
<5> *source files for new and published references*



Contributors interact almost exclusively with the `references` directory, as this is where source files are maintained.



[listing]
----
references                    # contains source files for published references
в”њв”Ђв”Ђ bin -> ../common/bin      # symbolic link to a shared scripts directory
в”њв”Ђв”Ђ partner-a                 # contains source files for all documents featuring the named partner
в”њв”Ђв”Ђ partner-b                 # contains source files for all documents featuring the named partner
...
в”њв”Ђв”Ђ partner-z                 # contains source files for all documents featuring the named partner
в””в”Ђв”Ђ suse                      # contains source files for SUSE-specific references
----



A getting started guide features a combination of components by one or more "entities," such as SUSE, a partner company, or an open source project.
The source files used to generate these guides are maintained under the _linux/start_ or _kubernetes/start_ directories, depending on the primary implementation focus.
Guide files are further organized into directories named for a featured entity.
This is typically the provider of the component at the highest layer of the technology stack and closest to the user's workload or use case.
Thus, for example, you find directories for Kubeflow, MongoDB, Ondat, and so on.

[listing]
----
start
в”њв”Ђв”Ђ bin
в”њв”Ђв”Ђ kubeflow
в”њв”Ђв”Ђ minio
в”њв”Ђв”Ђ mongodb
в”њв”Ђв”Ђ ondat
в”њв”Ђв”Ђ suse
в”њв”Ђв”Ђ sysdig
в”њв”Ђв”Ђ upbound
в””в”Ђв”Ђ veeam
----

[NOTE]
====
The _bin_ directory contains scripts to help contributors perform various tasks.
====

Inside an "entity" directory, you find further structure.
For example:

[listing]
----
veeam
в”њв”Ђв”Ђ DC-gs_rancher_veeam-kasten <1>
в”њв”Ђв”Ђ adoc <2>
в”‚В В  в”њв”Ђв”Ђ common_gfdl1.2_i.adoc -> ../../../../common/adoc/common_gfdl1.2_i.adoc
в”‚В В  в”њв”Ђв”Ђ ...
в”‚В В  в”њв”Ђв”Ђ gs_rancher_veeam-kasten.adoc <3>
в”‚В В  в””в”Ђв”Ђ gs_rancher_veeam-kasten-docinfo.xml <4>
в”њв”Ђв”Ђ images -> media
в””в”Ђв”Ђ media <5>
    в””в”Ђв”Ђ src
        в”њв”Ђв”Ђ png
        в”‚В В  в”њв”Ђв”Ђ rancher_veeam-kasten_k10_dashboard-welcome.png
        в”‚В В  в”њв”Ђв”Ђ ...
        в”‚   в””в”Ђв”Ђ rancher_veeam-kasten_architecture-1.png
        в””в”Ђв”Ђ svg
            в”њв”Ђв”Ђ logo-lockup_rancher-by-suse_kasten-by-veeam_hor_dark.svg
            в””в”Ђв”Ђ suse.svg -> ../../../../../../common/images/src/svg/suse.svg
----
<1> *Doc Config (DC) file*: There is one DC file for each documentation deliverable in which you specify parameters that define the name of the main content file, the rendering stylesheet, the revision date, and so on.
<2> *_adoc_ directory*: Contains your AsciiDoc content files and your DocBook metadata file.
<3> *Main content file*: This plain text file, formatted with the https://asciidoc.org/[AsciiDoc] markup language, is where you write most of the text of your document.
You can use the `include` directive to merge content from other AsciiDoc files during the rendering process.
<4> *DocBook metadata (docinfo.xml) file*: This file specifies metadata about your document, including title, author information, cover logo file, and executive summary.
Much of this information is actually defined as document attributes (variables) in your main content file and referenced here to save you from having to type the same information twice.
<5> *_media_ directory*: You can include logos, diagrams, screenshots, and other images in your guides.
These media files are stored in subdirectories by file type under _media/src_.
Many image file types are supported, but preference is given to:
+
--
* https://www.w3.org/Graphics/SVG/[Scaled Vector Graphics] or 'SVG' is a widely-deployed, royalty-free, vector graphics format developed and maintained by the W3C.
A vector graphics image is rendered from a set of instructions that defines the image from basic, geometric shapes.
This allows SVGs to be resized without loss of clarity.
SVGs are typically used for logos and architectural diagrams.
* https://en.wikipedia.org/wiki/PNG[Portable Network Graphics] or 'PNG' is a raster graphics format.
A raster image encodes information (like position, color, or brightness)  for each pixel (picture element) that makes up the image.
PNG uses lossless compression, allowing PNGs to be edited and resaved without loss of clarity (unlike Joint Photographic Experts Group or 'JPEG' images).
Scaling raster images can introduce artifacts.
This is particularly apparent when images are enlarged.
Choose image resolutions to minimize these artifacts.
--
+
[NOTE]
====
In the "entity" directory, _images_ is a symbolic link to the _media_ directory, and is used to maintain compatibility with existing processes and tooling.
====




